library(readr)
IP_DATA_ALL <- read_csv("D:/Datascience/Datascience/vkhcggit/practical-data-science/VKHCG/01-Vermeulen/00-RawData/IP_DATA_ALL.csv")
View(IP_DATA_ALL)
spec(IP_DATA_ALL)
>library(tibble)
set_tidy_names(IP_DATA_ALL, syntactic = TRUE, quiet = FALSE)
 sapply(IP_DATA_ALL, typeof)
 library(data.table)
  hist_country=data.table(Country=unique(IP_DATA_ALL[is.na(IP_DATA_ALL ['Country']) == 0, ]$Country))
  setorder(hist_country,'Country')
  hist_country_with_id=rowid_to_column(hist_country, var = "RowIDCountry")
View(hist_country)
IP_DATA_COUNTRY_FREQ=data.table(with(IP_DATA_ALL, table(Country))) 
View(IP_DATA_COUNTRY_FREQ) 
sapply(IP_DATA_ALL[,'Latitude'], min, na.rm=TRUE)
 sapply(IP_DATA_ALL[,'Country'], min, na.rm=TRUE)
  > sapply(IP_DATA_ALL[,'Latitude'], max, na.rm=TRUE)
   sapply(IP_DATA_ALL[,'Country'], max, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Latitude'], mean, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Latitude'], median, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Latitude'], range, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Latitude'], quantile, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Latitude'], sd, na.rm=TRUE)
   sapply(IP_DATA_ALL [,'Longitude'], sd, na.rm=TRUE)